[project]
name = "obj-detection"
version = "0.1.0"
description = "Object Detection Lab"
readme = "README.md"
requires-python = ">=3.10, <3.12"
dependencies = [
    "ipykernel",
    "jupyter",
    "pandas",
    "numpy<2.0.0",
    "torch==2.1.0",
    "torchvision==0.16.0",
    "mmcv==2.1.0",
    "mmdet>=3.3.0",
    "mmengine>=0.10.7",
    "selectivesearch>=0.4",
    "torchmetrics[detection]>=1.8.2",
]


[tool.uv]
find-links = [
    # PyTorch Wheels (CUDA 12.1) - Ensures Torch matches your GPU driver
    "https://download.pytorch.org/whl/cu121",
    "https://download.openmmlab.com/mmcv/dist/cu121/torch2.1.0/index.html"
]
